WebStoreUi/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStoreDomain.Abstract;
using WebStoreDomain.Concrete;
using WebStoreDomain.Entities;

namespace WebStoreUi.Controllers
{
    public class NavController : Controller
    {
        private IStoreRepository<Category> repository; //1 зависимость
        private IStoreRepository<Order> orderrepository; //1 зависимость
        private List<string> ordersState = new List<string>() { "new", "payd", "send", "done" };
        public NavController(IStoreRepository<Category> repositorycat, IStoreRepository<Order> orderrepositoryninject)
        {
           // repository = new CategoryRepository();//2 зависимость
            repository = repositorycat;
            orderrepository = orderrepositoryninject;
        }
        // GET: Nav
        public ActionResult Menu()
        {
            return PartialView(repository.Items);
        }
        public ActionResult OrderFilter()
        {
            return PartialView(ordersState);
        }
    }
}

WebStoreUi/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebStoreDomain.Abstract;
using WebStoreDomain.Concrete;
using WebStoreDomain.Entities;
using WebStoreUi.Models;

namespace WebStoreUi.Controllers
{
    public class ProductController : Controller
    {
        //dependency injection
        private IStoreRepository<Product> repository; //1 зависимость
        private IStoreRepository<Category> categrepository; //1 зависимость
        private int PageSize = 9;

        //public ProductController()
        //{
        //    repository = new ProductRepository();//2 зависимость
        //    categrepository = new CategoryRepository();
        //}

        public ProductController(IStoreRepository<Product> storeRepository, IStoreRepository<Category> storeRepository2)
        {
            repository = storeRepository; // there is no 2 injection 
            categrepository = storeRepository2;                          // categrepository = new CategoryRepository();
        }


        // GET: Product
        [AllowAnonymous]
        public ActionResult List(string searchparam  , string category, int? productname, int page = 1)
        {
            IQueryable<Product> arr = ((DbSet<Product>)repository.Items).Include("Category");

            //  if (!String.IsNullOrEmpty(productname) && !productname.Equals("Все"))
            if (productname != null && productname != 0)
            {
                page = 1;
                //int id = Int32.Parse(productname);
                arr = arr.Where(p => p.Id == productname);
            }
            List<Product> teams = ((DbSet<Product>)repository.Items).ToList();
            // устанавливаем начальный элемент, который позволит выбрать всех
            teams.Insert(0, new Product { Name = "Все", Id = 0 });

            var plvm = new ProductListViewModel
            {


            Products = arr
                            .Where(p => category == null || p.Category.Name == category)
                                .Where(s => searchparam == null || s.Name.Contains(searchparam))
                            .OrderBy(p => p.Id)
                            .Skip((page - 1) * PageSize)
                            .Take(PageSize),

            //    Products = repository
            //                .Items
            //                .Where(p=>category == null || p.Category.Name == category)
            //                .OrderBy(p => p.Id)
            //                .Skip((page - 1) * PageSize)
            //                .Take(PageSize),
            
            PagingInfo = new PagingInfo
                {
                TotalItems = arr.Where(p => category == null || p.Category.Name == category)
                                .Where(s => searchparam == null || s.Name.Contains(searchparam)).Count(),
                //TotalItems = repository.Items.Where(p => category == null || p.Category.Name == category).Count(),
                // TotalItems = repository.Items.Count(p => category == null || p.Category.Name == "For body"),
                ItemsPerPage = PageSize,
                    CurrentPage = page
                },
                CurrentCategory = category,
                CurrentItemSearch = searchparam,
                ProductNames = new SelectList(teams, "Id", "Name"),
            };

            return View(plvm);
        }
        [AllowAnonymous]
        public ActionResult PartislListForAjaxCategories(string category, int? productname, int page = 1)
        {
            IQueryable<Product> arr = ((DbSet<Product>)repository.Items).Include("Category");

            //  if (!String.IsNullOrEmpty(productname) && !productname.Equals("Все"))
            if (productname != null && productname != 0)
            {
                page = 1;
                //int id = Int32.Parse(productname);
                arr = arr.Where(p => p.Id == productname);
            }
            List<Product> teams = ((DbSet<Product>)repository.Items).ToList();
            // устанавливаем начальный элемент, который позволит выбрать всех
            teams.Insert(0, new Product { Name = "Все", Id = 0 });

            var plvm = new ProductListViewModel
            {


                Products = arr
                            .Where(p => category == null || p.Category.Name == category)
                            .OrderBy(p => p.Id)
                            .Skip((page - 1) * PageSize)
                            .Take(PageSize),

                //    Products = repository
                //                .Items
                //                .Where(p=>category == null || p.Category.Name == category)
                //                .OrderBy(p => p.Id)
                //                .Skip((page - 1) * PageSize)
                //                .Take(PageSize),

                PagingInfo = new PagingInfo
                {
                    TotalItems = arr.Where(p => category == null || p.Category.Name == category).Count(),
                    //TotalItems = repository.Items.Where(p => category == null || p.Category.Name == category).Count(),
                    // TotalItems = repository.Items.Count(p => category == null || p.Category.Name == "For body"),
                    ItemsPerPage = PageSize,
                    CurrentPage = page
                },
                CurrentCategory = category,
                ProductNames = new SelectList(teams, "Id", "Name"),
            };

            // return View(plvm);
            return PartialView(plvm);
        }




        [AllowAnonymous]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            // Находим в бд футболиста
            //е удалось привести тип объекта "System.Data.Entity.Infrastructure.DbQuery`1[WebStoreDomain.Entities.Product]" 
            //к типу "System.Data.Entity.DbSet`1[WebStoreDomain.Entities.Product]".

           // Product p = repository.Items.Where(p3=>p3.Id == id).FirstOrDefault();
           

          //  DbQuery<Product> dbq = ((DbQuery<Product>) pr);
          //  DbSet<Product> dbs0 = (DbSet<Product>)dbq;
          // Product pp2 = dbs0.Find(id);
          //DbSet<Product> dbs = ((DbSet<Product>)pr);
          //Product pp =  dbs.Find(id);

            Product p = await ((DbSet<Product>)repository.Items).FindAsync(id);
            if (p == null)
            {
                return HttpNotFound();
            }

            SelectList cat = new SelectList(categrepository.Items, "Id", "Name", p.CategoryId);
            ViewBag.Categ = cat;
            return View(p);

        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(Product p)
        {
            // Product p = db.Products.Find(id);
            if (p == null)
            {
                return HttpNotFound();
            }
           // Product p1 = repository.Items.Where(pr => pr.Id == p.Id).FirstOrDefault();
            Product p1 = await ((DbSet<Product>)repository.Items).FindAsync(p.Id);
            if (p1 == null)
            {
                return HttpNotFound();
            }


            SelectList cat = new SelectList(categrepository.Items, "Id", "Name", p.CategoryId);
            ViewBag.Categ = cat;
            return View(p1);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int id)
        {
          //    Product p =  repository.Items.Where(pr => pr.Id == id).FirstOrDefault();
            Product p = await ((DbSet<Product>)repository.Items).FindAsync(id);
            if (p == null)
            {
                return HttpNotFound();
            }

            ((DbSet<Product>)repository.Items).Remove(p);
            // ((DbContext)repository).SaveChanges();
           ((ProductRepository)repository).Context.SaveChanges();

            return RedirectToAction("List");
        }



        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Add()
        {
            SelectList categ = new SelectList(categrepository.Items, "Id", "Name");
            ViewBag.Categ = categ;
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Add(Product p)
        {
            ((DbSet<Product>)repository.Items).Add(p);
            await ((ProductRepository)repository).Context.SaveChangesAsync();

            //return View();
            return RedirectToAction("List");

        }



        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            // ModelState.IsValidField("Name"); 
            //  ModelState["Name"].Errors;
            // ModelState.AddModelError("Name", "ERROR");

           

            if (id == null)
                {
                    return HttpNotFound();
                }
                // Находим в бд футболиста
                Product p = await ((DbSet<Product>)repository.Items).FindAsync(id);
                if (p == null)
                {
                    return HttpNotFound();
                }

                SelectList cat = new SelectList(categrepository.Items, "Id", "Name", p.CategoryId);
                ViewBag.Categ = cat;
                return View(p);
          
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(Product p)
        {
            if (Regex.IsMatch(p.Name, @"^\w{3,}$"))
            {
                ModelState.AddModelError("Name","you entered wrong name");
            }


            if (ModelState.IsValid)
            {

WebStoreUi/Views/Shared/Footer.cshtml
<p>&copy; @DateTime.Now.Year</p>

WebStoreUi/Views/Shared/Footer1.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- здесь остальное содержание -->
@section Footer {
    Все права защищены. Syte Corp. 2012.
}

@section Footer1 {
    Все права защищены. Syte Corp. 2012.
    ads
    as
    da
    sdas
    <p>asdasdasd</p>
    <button>asdasd</button>
}

WebStoreUi/Views/Shared/NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            @Html.ActionLink("Dushka", "List", "Product", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Catalog", "List", "Product")</li>
                <li>@Html.ActionLink("About", "About", "Product")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Product")</li>


            </ul>

            <div>                
                    @Html.Action("Summary", "Cart")
            </div>

            @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("LogOut", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                {
                    @*@Html.AntiForgeryToken()*@
        <ul class="nav navbar-nav navbar-right">
            <li>
                Hello  @User.Identity.Name!
            </li>
            @*<li>
                <input style="" type="submit" value="Log out" />
            </li>*@

            <li>
                @Html.ActionLink("Log out", "Login", "Account")
            </li>

        </ul>
                }
            }
            else
            {
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @Html.ActionLink("Register", "Register", "Account",
                   routeValues: null,
                   htmlAttributes: new { id = "registerLink" })
                    </li>

                    <li>
                        @Html.ActionLink("Log in", "Login", "Account",
                   routeValues: new { returnUrl = Request.Url.PathAndQuery },
                   htmlAttributes: new { id = "loginLink" })
                    </li>
                </ul>
            }
        </div>
    </div>
</div>

WebStoreUi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />*@
    <script src="~/Scripts/modernizr-2.8.3.js"></script>


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@

</head>
<body>

    <header>
        @Html.Partial("NavBar")
    </header>


    @*<div style="display: block;">
        @Html.Action("Menu", "Nav")
    </div>*@

    @*<div style="display: block;">
        @Html.Action("OrderFilter", "Nav")
    </div>*@

    @*<div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>*@

    <div class="container body-content">
        @RenderBody()
    </div>
    <hr />

    @*@section Footer {
            Все права защищены. Syte Corp. 2012.
        }*@


    <footer>
        @Html.Partial("Footer")
    </footer>

    <footer>
        @if (IsSectionDefined("Footer1"))
        {
            @RenderSection("Footer1")
        }
        else
        {
            <span>Содержание элемента footer по умолчанию.</span>
        }
    </footer>


    @*<footer>@RenderSection("Footer1", false)</footer>*@



    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @*//до  jquery validate*@
    <script src="~/Scripts/vali"></script>
    @*@Scripts.Render()*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.js")

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)*@
</body>
</html>