WebStoreUi/Controllers/AdminProductController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebStoreDomain.Abstract;
using WebStoreDomain.Concrete;
using WebStoreDomain.Entities;
using WebStoreUi.Models;

namespace WebStoreUi.Controllers
{
    public class AdminProductController : Controller
    {
        private IStoreRepository<Product> repository; //1 зависимость
        private IStoreRepository<Category> categrepository; //1 зависимость
        private int PageSize = 5;
        //public AdminProductController()
        //{
        //    repository = new ProductRepository();//2 зависимость
        //    categrepository = new CategoryRepository();
        //}


        public AdminProductController(IStoreRepository<Product> storeRepository, IStoreRepository<Category> storeRepository2)
        {
            repository = storeRepository; // there is no 2 injection 
            categrepository = storeRepository2;                          // categrepository = new CategoryRepository();
        }



        // Выводим всех футболистов
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult AllProducts()
        {
            var players = ((DbSet<Product>)repository.Items).Include(p => p.Category);
            ViewBag.Product = players;
            return View(players.ToList());
        }



        [Authorize(Roles = "Admin")]
        public ActionResult List(string name, int page = 1)
        {
            var players = ((DbSet<Product>)repository.Items).Where(p => name == null ||  p.Name.Contains(name)).Include(p => p.Category).OrderBy(p => p.Id).Skip((page - 1) * PageSize).Take(PageSize);
            var plvm = new ProductListViewModel
            {
                Products= players,
                //Products = repository
                //           .Products
                //           .OrderBy(p => p.Id)
                //           .Skip((page - 1) * PageSize)
                //           .Take(PageSize).Include(p => p.Category),
                PagingInfo = new PagingInfo
                {
                    TotalItems = repository.Items.Where(p => name == null || p.Name.Contains(name)).Count(),
                    ItemsPerPage = PageSize,
                    CurrentPage = page
                },
                CurrentItemSearch = name

            };

            return View(plvm);

            //// IEnumerable<Product> products = (DbSet<Product>)repository.Products;
            // IEnumerable<Product> products = ((DbSet<Product>)repository.Products).Include(p => p.Category);
            // //ViewBag.Products = products;
            // return View(products);
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> ProductDetails(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            // Находим в бд футболиста
            Product p = await ((DbSet<Product>)repository.Items).FindAsync(id);
            if (p == null)
            {
                return HttpNotFound();
            }

           
            SelectList cat = new SelectList(categrepository.Items, "Id", "Name", p.CategoryId);
            ViewBag.Categ = cat;
            return View(p);

        }
                                    


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteProduct(Product p)
        {
            // Product p = db.Products.Find(id);
            if (p == null)
            {
                return HttpNotFound();
            }
            Product p1 = await ((DbSet<Product>)repository.Items).FindAsync(p.Id);
            if (p1 == null)
            {
                return HttpNotFound();
            }


            SelectList cat = new SelectList(categrepository.Items, "Id", "Name", p.CategoryId);
            ViewBag.Categ = cat;
            return View(p1);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteProduct(int id)
        {
            Product p = await ((DbSet<Product>)repository.Items).FindAsync(id);
            if (p == null)
            {
                return HttpNotFound();
            }

            ((DbSet<Product>)repository.Items).Remove(p);
            // ((DbContext)repository).SaveChanges();
            ((ProductRepository)repository).Context.SaveChanges();

            return RedirectToAction("List");
        }



        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult CreateProduct()
        {
            SelectList categ = new SelectList(categrepository.Items, "Id", "Name");
            ViewBag.Categ = categ;
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> CreateProduct(Product p)
        {
            ((DbSet<Product>)repository.Items).Add(p);
            await ((ProductRepository)repository).Context.SaveChangesAsync();

            //return View();
            return RedirectToAction("List");

        }



        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> EditProduct(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            // Находим в бд футболиста
            Product p = await ((DbSet<Product>)repository.Items).FindAsync(id);
            if (p == null)
            {
                return HttpNotFound();
            }

            SelectList cat = new SelectList(categrepository.Items, "Id", "Name", p.CategoryId);
            ViewBag.Categ = cat;
            return View(p);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> EditProduct(Product p)
        {
            ((ProductRepository)repository).Context.Entry(p).State = System.Data.Entity.EntityState.Modified;
            await ((ProductRepository)repository).Context.SaveChangesAsync();
            return RedirectToAction("List");
        }






      //  [HttpPost]
        public ActionResult ProductAdminSearch(string name, int page = 1)
        {
            var players = ((DbSet<Product>)repository.Items).Where(p => p.Name.Contains(name)).Include(p => p.Category)
                .OrderBy(p => p.Id).Skip((page - 1) * PageSize).Take(PageSize).ToList();
            if (players.Count <= 0)
            {
                //var plvm1 = new ProductListViewModel
                //{
                //    Products = new List<Product>() { new Product() },
                //    //Products = repository
                //    //           .Products
                //    //           .OrderBy(p => p.Id)
                //    //           .Skip((page - 1) * PageSize)
                //    //           .Take(PageSize).Include(p => p.Category),
                //    PagingInfo = new PagingInfo
                //    {
                //        //  TotalItems =repository.Items.Count(),
                //        TotalItems = 0,
                //        ItemsPerPage = PageSize,
                //        CurrentPage = page
                //    }
                //};
                //return PartialView(plvm1);
                return HttpNotFound("There are no such product");
              //  return PartialView();
            }
            var plvm = new ProductListViewModel
            {
                Products = players,
                //Products = repository
                //           .Products
                //           .OrderBy(p => p.Id)
                //           .Skip((page - 1) * PageSize)
                //           .Take(PageSize).Include(p => p.Category),
                PagingInfo = new PagingInfo
                {
                    //  TotalItems =repository.Items.Count(),
                    // TotalItems = players.Where(p => name == null || p.Name.Contains(name)).Count(),
                    TotalItems = ((DbSet<Product>)repository.Items).Where(p => p.Name.Contains(name)).Include(p => p.Category).ToList().Count(),
                    ItemsPerPage = PageSize,
                    CurrentPage = page
                },
                CurrentItemSearch = name
            };

            return PartialView(plvm);

            //var products = ((DbSet<Product>)repository.Items).Where(p => p.Name.Contains(name)).ToList();
           // return PartialView(products);
        }
      // public ActionResult Search() { return View(); }


    }
}

WebStoreUi/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebStoreUi.Controllers
{
    public class UploadController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Index1()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase upload)
        {
            if (upload != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(upload.FileName);
                // сохраняем файл в папку Files в проекте
                upload.SaveAs(Server.MapPath("~/Files/" + fileName));
            }
            return RedirectToAction("Index");
        }

        //Даже если мы все сделаем правильно, мы можем получить ошибку, если попытаемся загрузить файл размером больше 4 МБ.
        //4 мегабайта - ограничение, действующее на стороне сервера. Однако мы можм его переопределить.

        [HttpPost]
        public ActionResult UploadMany(IEnumerable<HttpPostedFileBase> uploads)
        {
            foreach (var file in uploads)
            {
                if (file != null)
                {
                    // получаем имя файла
                    string fileName = System.IO.Path.GetFileNameWithoutExtension(file.FileName);
                    string extension = System.IO.Path.GetExtension(file.FileName);

                    var Random = new Random();
                    fileName += Random.Next().ToString();
                    fileName += extension;

                  //  System.IO.Path.ChangeExtension(fileName, extension); 
                    // сохраняем файл в папку Files в проекте
                    file.SaveAs(Server.MapPath("~/Files/" + fileName));
                }
            }

            return RedirectToAction("Index");
        }
    }
}

WebStoreUi/Views/AdminProduct/AllProducts.cshtml
@model IEnumerable<WebStoreDomain.Entities.Product>

@{
    ViewBag.Title = "AllProducts";
}

<h2>AllProducts</h2>


@using WebStoreDomain.Entities;

<p>
    @Html.ActionLink("Добавить игрока", "Add")
</p>


@*<h2>@ViewBag.Product.Name</h2>
    <p>Price:@ViewBag.Product.Price </p>

    <p>@ViewBag.Product.Category.Name</p>*@

@*<p>@Model.Category.Name</p>*@

@*<p>@Html.DisplayFor(modelItem => Model.Name)</p>

    @Html.DisplayFor(modelItem => Model.Description)
    @Html.DisplayFor(modelItem => Model.Description)
    @Html.DisplayFor(modelItem => Model.Category.Name)*@






<table>
    <tr>
        <th>Имя игрока</th>
        <th>Возраст</th>
        <th>Description</th>
        <th>Команда</th>
        <th></th>
    </tr>

    @foreach (Product item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>



<p>
    @Html.ActionLink("Каталог команд", "ListTeams")
</p>    

WebStoreUi/Views/AdminProduct/DeleteProduct.cshtml
@model WebStoreDomain.Entities.Product

@{
    ViewBag.Title = "DeleteProduct";
}






<div style="text-align: center;">
    <h2>  @Html.DisplayFor(model => model.Name)</h2>
</div>

<div>
    <div style="float: left; width: 30%;">

        <div style="margin-left: 10%;">
            <img src="@Url.Content(Model.Src)" style="margin: 4px; width: 90%; height: 98%;" />
        </div>

    </div>
    <div style="float: right; width: 68%;">
        @*<h4>Product</h4>*@
        @*<hr />*@
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Volume)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Volume)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.InStoke)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.InStoke)
            </dd>

            @*<dt>
                @Html.DisplayNameFor(model => model.Src)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Src)
            </dd>*@

            <dt>
                @Html.DisplayNameFor(model => model.Category)
            </dt>

            <dd>
                @Html.DropDownListFor(model => model.Category, ViewBag.Categ as SelectList)
                @* @Html.DisplayFor(ViewBag.Categ as SelectList)*@
            </dd>
            <dt></dt>
            <dd>             
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color"  style="margin-top: 10px; margin-left: 10px;">
                        <input type="submit" value="Delete" class="btn btn-default" />

                    </div>
                }
        </dd>
        </dl>
      
    </div>
</div>

<footer style="clear: both;  ">
    <div style="width: 100%;  margin-left: 11%;">

        @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id })*@
        @*@Html.ActionLink("Back to List", "Index")*@


        <a href=@Url.Action("List", "AdminProduct") style="text-decoration:none; color: black;">
            <button type="button" class="btn btn-success btn-sm">  <i class="fa fa-edit" style="color:black">Back to List</i></button>
        </a>


    </div>
</footer>
















@*<h2>DeleteProduct</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Product</h4>
        <hr />
        <dl class="dl-horizontal">


            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Volume)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Volume)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.InStoke)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.InStoke)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Src)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Src)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.Category)
            </dt>

            <dd>
                @Html.DropDownListFor(model => model.Category, ViewBag.Categ as SelectList)
            </dd>


        </dl>

        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>*@

WebStoreUi/Views/AdminProduct/EditProduct.cshtml
@model WebStoreDomain.Entities.Product

@{
    ViewBag.Title = "EditProduct";
}

<h2>EditProduct</h2>

<div>
    <div style="float: left; width: 30%;">

        <div style="margin-left: 10%;">
            <img src="@Url.Content(Model.Src)" style="margin: 4px; width: 90%; height: 98%;" />
        </div>

    </div>

    <div style="float: right; width: 68%;">


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Product</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Volume, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Volume, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Volume, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.InStoke, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.InStoke)
                            @Html.ValidationMessageFor(model => model.InStoke, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">

                 


                        @*@using (Ajax.BeginForm("UploadMany", "Upload", new AjaxOptions
                        {
                            HttpMethod = "POST",
                            UpdateTargetId = "AjaxUpdatePanel"
                        }, new { enctype = "multipart/form-data", id = "frmUploader" }))
                        {
                            <div style="position:relative;">
                                <a class='btn btn-primary' href='javascript:;'>
                                    Choose File...
                                    <input type="file" name="uploads" value="F;LDFVKJ" style='position:absolute;z-index:2;top:0;left:0;filter: alpha(opacity=0);-ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
        opacity:0;background-color:transparent;color:transparent;' size="40" onchange='$("#upload-file-info").html($(this).val());'>
                                </a>
                                &nbsp;
                                <span class='label label-info' id="upload-file-info"></span>
                            </div><br />
                            <div style="position:relative;">
                                <a class='btn btn-primary' href='javascript:;'>
                                    Choose File...
                                    <input type="file" name="uploads" value="F;LDFVKJ" style='position:absolute;z-index:2;top:0;left:0;filter: alpha(opacity=0);-ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
        opacity:0;background-color:transparent;color:transparent;' size="40" onchange='$("#upload-file-info1").html($(this).val());'>
                                </a>
                                &nbsp;
                                <span class='label label-info' id="upload-file-info1"></span>
                            </div><br />
                            <div style="position:relative;">
                                <a class='btn btn-primary' href='javascript:;'>
                                    Choose File...
                                    <input type="file" name="uploads" value="F;LDFVKJ" style='position:absolute;z-index:2;top:0;left:0;filter: alpha(opacity=0);-ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
        opacity:0;background-color:transparent;color:transparent;' size="40" onchange='$("#upload-file-info2").html($(this).val());'>
                                </a>
                                &nbsp;
                                <span class='label label-info' id="upload-file-info2"></span>
                            </div><br />
                            <input type="submit" value="Upload" />
                        }
                        <div id="AjaxUpdatePanel">*@

                            @Html.LabelFor(model => model.Src, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Src, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Src, "", new { @class = "text-danger" })
                            </div>
                        @*</div>*@
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Category, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.CategoryId, ViewBag.Categ as SelectList, htmlAttributes: new { @class = "form-control" })
                            @*@Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })*@
                            @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                        </div>

                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
        }
    </div>
</div>


<footer style="clear: both;  ">
    <div style="width: 100%;  margin-left: 11%;">

        @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id })*@
        @*@Html.ActionLink("Back to List", "Index")*@


        <a href=@Url.Action("List", "AdminProduct") style="text-decoration:none; color: black;">
            <button type="button" class="btn btn-success btn-sm">  <i class="fa fa-edit" style="color:black">Back to List</i></button>
        </a>


    </div>
</footer>


@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

WebStoreUi/Views/AdminProduct/List.cshtml
@using WebStoreDomain.Entities
@using WebStoreUi.HtmlHelpers
@using WebStoreUi.Models


@*@model  IEnumerable<Product>*@
@model ProductListViewModel

@{
    ViewBag.Title = "Goods";
}

@{ WebStoreDomain.Entities.Product pr = null; }
<h2>List</h2>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<div>
    <div style="float: left; width: 40%; display: inline">
        <p>
            <button type="button" class="btn btn-success "><i class="fa fa-plus" style="color:black">@Html.ActionLink("Create New", "CreateProduct", null, new { style = "text-decoration:none; color: black;" })</i></button>
            <button type="button" class="btn btn-success "><i class="fa fa-plus" style="color:black">@Html.ActionLink("Upload images", "Index", "Upload", null, new { style = "text-decoration:none; color: black;" })</i></button>

        </p>
      
    </div>
    

    <div style="float: right; width: 58%;">
        @using (Ajax.BeginForm("ProductSearch", new AjaxOptions
        {
            UpdateTargetId = "adminproductresults",
            LoadingElementId = "loading",
            LoadingElementDuration = 200,
            InsertionMode = InsertionMode.Replace
        }))
        {
            <div style="display: inline; display: flex; justify-content: flex-end ">

                @*<div class="form-group">*@
                @*<label for="formGroupExampleInput">Example label</label>*@
                <input style="display: inline" type="text" name="name" @*ПАРАМЕТР ИМЯ МЕТОДА  ProductsSearch*@ class="form-control" placeholder="Search" id="formGroupExampleInput" />
                <input type="submit" value="Search" class="btn btn-success" style="color: black; display: inline " />
                @*</div>*@
            </div>
        }
        <div id="loading" style="display: none;">Loading...</div>
    </div>
</div>
   

<div id="adminproductresults">

    <table class="table">
        <tr>
            @*<th>
                    @Html.DisplayNameFor(model => model.Category.Name)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => pr.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => pr.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => pr.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => pr.Volume)
            </th>
            <th>
                @Html.DisplayName("InStoke")
            </th>
            <th>
                @Html.DisplayNameFor(model => pr.Category)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Products)
        {
            <tr>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Category.Name)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Volume)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InStoke)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Src)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    <div>
                        <button type="button" class="btn btn-success btn-sm" style="margin-top:1px"><i class="fa fa-edit" style="color:black">@Html.ActionLink("Edit", "EditProduct", new { id = item.Id }, new { style = "text-decoration:none; color: black;" })</i></button>
                        <button type="button" class="btn btn-success btn-sm" style="margin-top:1px"><i class="fa fa-info-circle" style="color:black">@Html.ActionLink("Details", "ProductDetails", new { id = item.Id }, new { style = "text-decoration:none; color: black;" })</i></button>
                        <button type="button" class="btn btn-success btn-sm" style="margin-top:1px"><i class="fa fa-close" style="color:black">@Html.ActionLink("Delete", "DeleteProduct", new { id = item.Id }, new { style = "text-decoration:none; color: black;" })</i></button>

                    </div>
                    @*@Html.ActionLink("Edit", "EditProduct", new { id = item.Id }) |
                        @Html.ActionLink("Details", "ProductDetails", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "DeleteProduct", new { id = item.Id })*@
                </td>
            </tr>
        }

    </table>


    <div>
        @Html.PageLinks(Model.PagingInfo, i => Url.Action("List", new { page = i, name  = Model.CurrentItemSearch }))
    </div>
</div>